package com.mailanalyzer.entity;

import com.mailanalyzer.enums.EmailCategory;
import com.mailanalyzer.enums.EmailPriority;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.Instant;
import java.util.UUID;

/**
 * An analyzed email record.
 *
 * <p><b>Privacy guarantee:</b> This entity stores ONLY metadata and the
 * AI-generated summary. The raw email body, attachments, and full content
 * are NEVER persisted anywhere in the system.
 *
 * <p>The {@code gmailMessageId} field is used for duplicate detection.
 * Before inserting a new record, {@link com.mailanalyzer.repository.EmailRepository#existsByGmailMessageId(String)}
 * is checked to prevent re-analyzing the same email.
 */
@Entity
@Table(
    name = "emails",
    indexes = {
        @Index(name = "idx_email_user_id",       columnList = "user_id"),
        @Index(name = "idx_email_category",       columnList = "category"),
        @Index(name = "idx_email_priority",       columnList = "priority"),
        @Index(name = "idx_email_received_at",    columnList = "received_at"),
        @Index(name = "idx_email_source_account", columnList = "source_account")
    }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Email {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Owner of this email record. Every query MUST filter by this field. */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /**
     * Gmail's unique message ID.
     * Used for deduplication: {@link com.mailanalyzer.repository.EmailRepository#existsByGmailMessageId(String)}.
     */
    @Column(name = "gmail_message_id", nullable = false, unique = true, length = 255)
    private String gmailMessageId;

    /**
     * The Gmail address from which this email was fetched.
     * Allows the user to see which of their connected accounts received it.
     */
    @Column(name = "source_account", nullable = false, length = 255)
    private String sourceAccount;

    /** Sender display name and address (e.g. "LinkedIn <jobs@linkedin.com>"). */
    @Column(name = "sender", length = 500)
    private String sender;

    @Column(name = "subject", columnDefinition = "TEXT")
    private String subject;

    /**
     * 1–2 sentence summary generated by Gemini.
     * This is the ONLY AI output stored; raw email content is never persisted.
     */
    @Column(name = "summary", columnDefinition = "TEXT")
    private String summary;

    @Enumerated(EnumType.STRING)
    @Column(name = "category", nullable = false, length = 100)
    private EmailCategory category;

    /** Integer representation of the priority (1–5). */
    @Enumerated(EnumType.ORDINAL)
    @Column(name = "priority", nullable = false)
    private EmailPriority priority;

    /** When the email was originally sent/received (UTC). */
    @Column(name = "received_at")
    private Instant receivedAt;

    /** When AI analysis was completed for this email (UTC). */
    @CreationTimestamp
    @Column(name = "analyzed_at", updatable = false)
    private Instant analyzedAt;
}
